import React from 'react';
import ReactDOM from 'react-dom';
import DummyHeader from './component/DummyHeader';
import DummyArticle from './component/DummyArticle';
import DummySidebar from './component/DummySidebar';

const myMenu = [{label: 'Home', link: '#', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta eligendi eos expedita ipsam nemo quis repudiandae! Aperiam at id libero minima omnis quod recusandae reiciendis? Accusantium ad animi beatae excepturi iusto. Accusantium ad aliquid amet deserunt eaque, exercitationem fugiat, libero maxime odio porro quo repellendus reprehenderit unde. Ad, adipisci at beatae dolor doloremque eaque excepturi explicabo id in iusto labore magnam maiores necessitatibus obcaecati optio quibusdam ratione sed tempora tempore temporibus? Cupiditate eveniet illum quis. Ad adipisci aliquam consequatur cupiditate delectus deserunt eaque enim ipsa ipsam iste itaque labore laboriosam minus nemo perspiciatis quidem quo quod repellendus, sint suscipit veniam vero voluptatibus! Accusamus accusantium architecto blanditiis debitis, dicta distinctio dolorem doloribus ducimus enim, eos ex explicabo id impedit incidunt iste iusto laudantium libero nemo nisi nostrum quae quia quo quos reiciendis rem repellat repudiandae temporibus veritatis vitae voluptas? Architecto deserunt incidunt ipsa quae voluptate. Adipisci assumenda deserunt dolore error minima modi natus omnis provident, quo voluptatum. Ad beatae dolores enim eveniet ipsam nemo nobis repudiandae suscipit, unde. Culpa cumque explicabo molestiae perspiciatis quas sint. Adipisci delectus deleniti deserunt eos excepturi fugiat in incidunt itaque laborum nihil non, pariatur perferendis placeat quidem quis repellat, reprehenderit vero. Cum nemo recusandae vitae.'},
    {label: 'Contact', link: '#', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta eligendi eos expedita ipsam nemo quis repudiandae! Aperiam at id libero minima omnis quod recusandae reiciendis? Accusantium ad animi beatae excepturi iusto. Accusantium ad aliquid amet deserunt eaque, exercitationem fugiat, libero maxime odio porro quo repellendus reprehenderit unde. Ad, adipisci at beatae dolor doloremque eaque excepturi explicabo id in iusto labore magnam maiores necessitatibus obcaecati optio quibusdam ratione sed tempora tempore temporibus? Cupiditate eveniet illum quis. Ad adipisci aliquam consequatur cupiditate delectus deserunt eaque enim ipsa ipsam iste itaque labore laboriosam minus nemo perspiciatis quidem quo quod repellendus, sint suscipit veniam vero voluptatibus! Accusamus accusantium architecto blanditiis debitis, dicta distinctio dolorem doloribus ducimus enim, eos ex explicabo id impedit incidunt iste iusto laudantium libero nemo nisi nostrum quae quia quo quos reiciendis rem repellat repudiandae temporibus veritatis vitae voluptas? Architecto deserunt incidunt ipsa quae voluptate. Adipisci assumenda deserunt dolore error minima modi natus omnis provident, quo voluptatum. Ad beatae dolores enim eveniet ipsam nemo nobis repudiandae suscipit, unde. Culpa cumque explicabo molestiae perspiciatis quas sint. Adipisci delectus deleniti deserunt eos excepturi fugiat in incidunt itaque laborum nihil non, pariatur perferendis placeat quidem quis repellat, reprehenderit vero. Cum nemo recusandae vitae.'},
    {label: 'Shop', link: '#', text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum dicta eligendi eos expedita ipsam nemo quis repudiandae! Aperiam at id libero minima omnis quod recusandae reiciendis? Accusantium ad animi beatae excepturi iusto. Accusantium ad aliquid amet deserunt eaque, exercitationem fugiat, libero maxime odio porro quo repellendus reprehenderit unde. Ad, adipisci at beatae dolor doloremque eaque excepturi explicabo id in iusto labore magnam maiores necessitatibus obcaecati optio quibusdam ratione sed tempora tempore temporibus? Cupiditate eveniet illum quis. Ad adipisci aliquam consequatur cupiditate delectus deserunt eaque enim ipsa ipsam iste itaque labore laboriosam minus nemo perspiciatis quidem quo quod repellendus, sint suscipit veniam vero voluptatibus! Accusamus accusantium architecto blanditiis debitis, dicta distinctio dolorem doloribus ducimus enim, eos ex explicabo id impedit incidunt iste iusto laudantium libero nemo nisi nostrum quae quia quo quos reiciendis rem repellat repudiandae temporibus veritatis vitae voluptas? Architecto deserunt incidunt ipsa quae voluptate. Adipisci assumenda deserunt dolore error minima modi natus omnis provident, quo voluptatum. Ad beatae dolores enim eveniet ipsam nemo nobis repudiandae suscipit, unde. Culpa cumque explicabo molestiae perspiciatis quas sint. Adipisci delectus deleniti deserunt eos excepturi fugiat in incidunt itaque laborum nihil non, pariatur perferendis placeat quidem quis repellat, reprehenderit vero. Cum nemo recusandae vitae.'} ];

ReactDOM.render(
    <div>
        <DummyHeader data={myMenu}/>
        <div className="row">
            <DummyArticle />
            <DummySidebar/>
        </div>
    </div>
    , document.getElementById('app')
);